[workspace]
members = ["sdf_glyph_renderer", "pbf_font_tools", "build_pbf_glyphs"]
resolver = "2"

[workspace.package]
authors = ["Ian Wagner <ian@stadiamaps.com>", "Luke Seelenbinder <luke@stadiamaps.com>", "Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/stadiamaps/sdf_font_tools"
rust-version = "1.87.0"

[workspace.dependencies]
clap = { version = "4.5.60", features = ["derive"] }
freetype-rs = { version = "0.38.0", features = ["bundled"] }
futures = "0.3.32"
pbf_font_tools = { version = "4.0.0", path = "pbf_font_tools", features = ["freetype"] }
prost = "0.14.3"
prost-build = "0.14.3"
protobuf-src = "2.1.1"
protoc-bin-vendored = "3.2.0"
sdf_glyph_renderer = { version = "2.0.0", path = "sdf_glyph_renderer", features = ["freetype"] }
serde_json = "1.0.149"
spmc = "0.3.0"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["rt", "fs", "io-util"] }
