[package]
name = "pbf_font_tools"
version = "3.1.0"
description = "Tools for working with SDF font glyphs encoded in protobuf format."
readme = "README.md"
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["protoc-vendored"]
freetype = ["dep:sdf_glyph_renderer", "sdf_glyph_renderer?/freetype"]
freetype-system = ["dep:sdf_glyph_renderer", "sdf_glyph_renderer?/freetype-system"]
ttf-parser = ["dep:sdf_glyph_renderer", "sdf_glyph_renderer?/ttf-parser"]
protoc-from-src = ["dep:protobuf-src"]
protoc-vendored = ["dep:protoc-bin-vendored"]

[dependencies]
futures.workspace = true
prost.workspace = true
sdf_glyph_renderer = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "io-util", "macros"] }

[build-dependencies]
prost-build.workspace = true
protobuf-src = { workspace = true, optional = true }
protoc-bin-vendored = { workspace = true, optional = true }
