[package]
name = "pbf_font_tools"
version = "3.1.0"
description = "Tools for working with SDF font glyphs encoded in protobuf format."
readme = "README.md"
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
freetype = ["dep:sdf_glyph_renderer", "sdf_glyph_renderer?/freetype"]
freetype-system = ["dep:sdf_glyph_renderer", "sdf_glyph_renderer?/freetype-system"]
# Regenerate the protobuf source file using protoc, and write it back to the source tree.
# Combine with protoc-vendored or protoc-from-src to control which protoc binary is used.
# Without either of those features, protoc must be available in $PATH.
force-protobuf-gen = ["dep:prost-build"]
protoc-from-src = ["force-protobuf-gen", "dep:protobuf-src"]
protoc-vendored = ["force-protobuf-gen", "dep:protoc-bin-vendored"]

[dependencies]
futures.workspace = true
prost.workspace = true
sdf_glyph_renderer = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "io-util", "macros"] }

[build-dependencies]
prost-build = { workspace = true, optional = true }
protobuf-src = { workspace = true, optional = true }
protoc-bin-vendored = { workspace = true, optional = true }
