[package]
name = "pbf_font_tools"
version = "3.0.0"
description = "Tools for working with SDF font glyphs encoded in protobuf format."
readme = "README.md"
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["protoc-from-src"]
freetype = ["dep:sdf_glyph_renderer"]
protoc-from-src = ["dep:protobuf-src"]
protoc-bin-vendored = ["dep:protoc-bin-vendored"]

[target.'cfg(windews)'.features]
# Don't enable the protobuf source build on Windows by default.
# See https://github.com/MaterializeInc/rust-protobuf-native/issues/4
default = ["protoc-bin-vendored"]

[dependencies]
futures.workspace = true
prost.workspace = true
sdf_glyph_renderer = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "io-util", "macros"] }

[build-dependencies]
prost-build.workspace = true
protobuf-src = {workspace = true, optional = true}
protoc-bin-vendored = { workspace = true, optional = true }
