[package]
name = "build_pbf_glyphs"
version = "1.5.1"
description = "A CLI utility for generating protobuf-encoded SDF font glyphs from original source fonts."
readme = "README.md"
keywords = ["sdf", "protobuf", "fonts"]
categories = ["encoding", "parsing", "rendering::data-formats"]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
protoc-from-src = ["pbf_font_tools/protoc-from-src"]
protoc-vendored = ["pbf_font_tools/protoc-vendored"]

[dependencies]
clap.workspace = true
pbf_font_tools = { workspace = true, features = ["freetype"] }
prost.workspace = true
serde_json.workspace = true
spmc.workspace = true
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "macros"] }
