name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: cargo hack check --rust-version --workspace --all-targets --ignore-private

  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2

  test:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'

      - name: Report Rust version
        run: rustc --version && cargo --version

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Test Debug
        run: cargo test --workspace --all-features --locked

      - name: Test Release
        run: cargo test --workspace --release --all-features --locked

      - name: Lint
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Test docs
        run: |
          cargo test --workspace --release --doc --locked
          RUSTDOCFLAGS="-D warnings" cargo doc --workspace --release --no-deps


  multi-os-test:
    name: Test on multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # This is not an exhaustive list of runners, just the more recent ones
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-latest
          - macos-13
          - macos-14  # M1 CPU
          - windows-latest
          - windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'

      - name: Report Rust version
        run: rustc --version && cargo --version

      - name: Run tests
        run: cargo test --workspace --all-features --locked
