// This file is @generated by prost-build.
/// Stores a glyph with metrics and optional SDF bitmap information.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Glyph {
    #[prost(uint32, required, tag = "1")]
    pub id: u32,
    /// A signed distance field of the glyph with a border of 3 pixels.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub bitmap: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Glyph metrics.
    #[prost(uint32, required, tag = "3")]
    pub width: u32,
    #[prost(uint32, required, tag = "4")]
    pub height: u32,
    #[prost(sint32, required, tag = "5")]
    pub left: i32,
    #[prost(sint32, required, tag = "6")]
    pub top: i32,
    #[prost(uint32, required, tag = "7")]
    pub advance: u32,
}
/// Stores fontstack information and a list of faces.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fontstack {
    #[prost(string, required, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, required, tag = "2")]
    pub range: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub glyphs: ::prost::alloc::vec::Vec<Glyph>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Glyphs {
    #[prost(message, repeated, tag = "1")]
    pub stacks: ::prost::alloc::vec::Vec<Fontstack>,
}
